### ISSUE TITLE
Adding a new player places the player at the end of the list i.e. not sorted

### ISSUE THREAD

**Issue by NicholasMohr** [neil-lobracco/tracker#1]
You could say this is intentional or not worth fixing but just figured I would give the opportunity for thought!

Also I get to be the first issue on this repo 🎉

**Comment by neil-lobracco** [comment]
Good point! The server sorts them by Elo rating, but when creating, we just add it directly to the list rather than refetch the list of players. It should be simple enough to just insert it into the correct spot.

**Comment by neil-lobracco** [comment]
Fixed in https://github.com/neil-lobracco/tracker/commit/d9fc4678ba2d19feff97a2e8d7cea45b8b455e3d , in production.
